# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Update Tests Coverage

on:
  push:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build:
    name: Go test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Test with coverage
        run: go test -coverprofile=coverage.out -v ./...

      - name: Generate coverage percentage
        id: coverage
        run: |
          go tool cover -func=coverage.out | grep total | awk '{print $3}' > coverage.txt
          COVERAGE=$(cat coverage.txt | sed 's/%//')
          echo "coverage=$COVERAGE" >> $GITHUB_ENV

      - name: Generate Coverage Badge
        id: badge
        run: |
          COVERAGE=$(echo ${{ env.coverage }})
          
          COLOR="red"
          if (( $(echo "$COVERAGE < 50" | bc -l) )); then
            COLOR="red"
          elif (( $(echo "$COVERAGE >= 50 && $COVERAGE < 80" | bc -l) )); then
            COLOR="yellow"
          elif (( $(echo "$COVERAGE >= 80" | bc -l) )); then
            COLOR="green"
          else
            COLOR="gray"
          fi
          
          echo "https://img.shields.io/badge/Coverage-${COVERAGE}%25-${COLOR}.svg" > badge-url.txt

      - name: Commit coverage badge
        continue-on-error: true
        run: |
          BADGE_URL=$(cat badge-url.txt)
          echo "![Coverage Badge](${BADGE_URL})" > coverage-badge.md
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add coverage-badge.md
          git commit -m "Update coverage badge"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
