# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Update Tests Coverage

on:
  push:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build:
    name: Go test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -v ./...

      - name: Run tests and generate coverage badge
        id: badge
        run: |
          go test -coverprofile=coverage.out ./...
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
          echo "Coverage: $COVERAGE"
          
        
          COLOR="red"
          if (( $(echo "$COVERAGE < 50" | bc -l) )); then
            COLOR="red"
          elif (( $(echo "$COVERAGE >= 50 && $COVERAGE < 80" | bc -l) )); then
            COLOR="yellow"
          elif (( $(echo "$COVERAGE >= 80 && $COVERAGE < 90" | bc -l) )); then
            COLOR="green"
          elif (( $(echo "$COVERAGE >= 90" | bc -l) )); then
            COLOR="brightgreen"
          else
            COLOR="gray"
          fi
          
          BADGE_MARKDOWN="![Coverage](https://img.shields.io/badge/coverage-${COVERAGE}%25-${BADGE_COLOR})"
          echo "Updating README.md with the new badge..."
          
          sed -i "s|\\[!\\[Coverage\\](.*\\)|$BADGE_MARKDOWN|g" README.md

      - name: Commit coverage badge
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update coverage badge to $COVERAGE%"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
